name: Release static assets

env:
  PROJECT_NAME: 'demo'

on:
  workflow_dispatch:
  push:
    branches: ["develop", "gay"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Extract branch name
      shell: bash
      run: echo "BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV && echo "RELEASE_DATE=date +'%Y%m%d%H%M'"

    - name: Conventional Changelog Action
      id: changelog
      uses: TriPSs/conventional-changelog-action@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        output-file: "false"
        version-file: ${{env.BRANCH == 'gay' && './gay-version.json' || './package.json'}}

    - name: Create Release
      uses: actions/create-release@v1
      if: ${{ steps.changelog.outputs.skipped == 'false' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "${{ env.BRANCH == 'gay' && env.RELEASE_DATE || steps.changelog.outputs.tag }}-${{env.BRANCH}}"
        release_name: ${{env.BRANCH}} - ${{ env.BRANCH == 'gay' && env.RELEASE_DATE || steps.changelog.outputs.tag }}
        body: ${{ steps.changelog.outputs.clean_changelog }}